name: e2e Tests
on: [push, pull_request]
jobs:
  jest:
    name: e2e tests
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v3
      
      - run: ./run.sh
        working-directory: ./test