name: Update WordPress
on:
  schedule:
  - cron: "0 0 * * *"
  workflow_dispatch:
jobs:
  update:
    name: Update WordPress
    runs-on: ubuntu-latest
    if: github.repository_owner == 'mitchmac'
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - run: ./upgrade-wp.sh
        working-directory: ./util
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          commit-message: Automated WordPress version update
          title: WordPress version update
          body: 'This is an automated update of the bundled WordPress files'
          committer: "Mitch MacKenzie <mitchmac@gmail.com>"
          assignees: mitchmac
          delete-branch: true
          branch: 'wordpress-version-update'
